#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Apr 01, 2026 10:34:34 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import desing1

_debug = True # False to eliminate debug printing from callback functions.
_i = 0 

# --- CAMBIO 4: Creamos la función para enviar el mensaje ---
def enviar_mensaje():
    global _i
    if _debug:
        print('Botón Enviar presionado...')
    
    if _i == 0 :
      _w1.Text2.delete("1.0", tk.END)

    # 1. Obtenemos el texto escrito en Text1 (desde la línea 1, carácter 0 hasta el final)
    texto_ingresado = _w1.Text1.get("1.0", tk.END).strip()
    
    if texto_ingresado:
        # 2. Actualizamos la variable del Message1 con el texto obtenido
        if _i == 0:
          aux_text=f"Hola {texto_ingresado}!\n\n"
        else:
          aux_text=f"{texto_ingresado}\n\n"
        _w1.Text2.insert(tk.END,aux_text)
        
        # 3. Limpiamos la caja de texto para el siguiente mensaje
        _w1.Text1.delete("1.0", tk.END)
        match _i:
            case 0:
                _w1.mensaje_var.set("¿Quieres un sandwich? si/no")
                _i = 1
            case 1:
                if texto_ingresado.lower() == "no" :
                  _w1.mensaje_var.set("Gracias por usar este programa")
                  _i = 0
                  _w1.Text1.delete("1.0", tk.END)
                  _w1.Text2.delete("1.0", tk.END)
                  _w1.mensaje_var.set("¿Cómo te llamas?")
                  _w1.Text2.insert("1.0", "esperando tu orden..\n\n")
                else:
                  _w1.mensaje_var.set("¿Tu sandwich llevará mayonesa? si/no")
                  _i = 2
            case _:
                _w1.mensaje_var.set("dato no valido, el programa ha fallado.")
                if _debug:
                  print("err01: dato no valido, el programa ha fallado debido a que match no tiene coincidencia.")
                root.destroy()
    else:
        # Si el usuario presiona el botón sin escribir nada
        _w1.mensaje_var.set("Por favor, escribe algo antes de enviar.")
        # _w1.Text2.delete("1.0", tk.END)


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = desing1.Toplevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    desing1.start_up()
