#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Apr 01, 2026 10:33:58 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import desing1_support

_bgcolor = 'SystemButtonFace'
_fgcolor = 'SystemWindowText'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40'

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+340+90")
        top.minsize(120, 1)
        top.maxsize(2564, 701)
        top.resizable(1,  1)
        top.title("Sandwich app created by MigueGS")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.233, rely=0.067, height=51, width=324)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#b4b4b4")
        self.Label1.configure(font="-family {Impact} -size 16")
        self.Label1.configure(foreground="#517ef9")
        self.Label1.configure(highlightcolor="SystemWindowText")
        self.Label1.configure(text='''¡Bienvenido!''')

        self.Message1 = tk.Message(self.top)
        self.Message1.place(relx=0.3, rely=0.222, relheight=0.042, relwidth=0.417)
        self.Message1.configure(foreground="SystemWindowText")
        self.Message1.configure(highlightcolor="SystemWindowText")
        self.Message1.configure(justify='center')
        self.Message1.configure(padx="1")
        self.Message1.configure(pady="1")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=250)

        # --- CAMBIO 3: Creamos una variable de control para dinamizar el texto ---
        self.mensaje_var = tk.StringVar()
        self.mensaje_var.set("¿cómo te llamas?:")
        self.Message1.configure(textvariable=self.mensaje_var)

        self.Text1 = tk.Text(self.top)
        self.Text1.place(relx=0.3, rely=0.267, relheight=0.053, relwidth=0.423)
        self.Text1.configure(background="white")
        self.Text1.configure(exportselection="0")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(highlightcolor="SystemWindowText")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")
        self.Text1.bind("<Return>", lambda event: desing1_support.enviar_mensaje())

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.633, rely=0.333, height=26, width=47)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#b4b4b4")
        self.Button1.configure(foreground="SystemWindowText")
        self.Button1.configure(highlightcolor="SystemWindowText")
        self.Button1.configure(text='''Enviar''')
        
        # --- CAMBIO 1: Enlazamos el botón a la función de soporte ---
        self.Button1.configure(command=desing1_support.enviar_mensaje)

        self.Text2 = tk.Text(self.top)
        self.Text2.place(relx=0.283, rely=0.489, relheight=0.32, relwidth=0.457)
        self.Text2.configure(background="white")
        self.Text2.configure(exportselection="0")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(highlightcolor="SystemWindowText")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Text2.insert("1.0","esperando respuesta..\n\n")

def start_up():
    desing1_support.main()

if __name__ == '__main__':
    desing1_support.main()




